# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      # Step 1: obtain repo from GitHub
      - checkout
      # Step 2: create virtual env and install dependencies
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip

      # Step 3: pytest
      - run:
          name: run test
          command: |
            . venv/bin/activate
            pytest
      # Step 4: Sonar cloud report
      - sonarcloud/scan
workflows:
  main:
    jobs:
      - build:
          context: sonarcloud